alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee drop foreign key FKbejtwvg9bxus2mffsm3swj3u9;
drop table if exists department;
drop table if exists employee;
create table department (id bigint(10) not null auto_increment, name varchar(50) not null, director varchar(255), primary key (id)) engine=InnoDB;
create table employee (department_id bigint(10), id bigint(10) not null auto_increment, name varchar(50) not null, email varchar(255), manager varchar(255), primary key (id)) engine=InnoDB;
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
